__name__ = 'PressCheck'
__description__ = '2020-2 Sejong University Capstone Project: PressCheck'
__version__ = '0.0.0'
__url__ = 'https://github.com/reyeon1209/PressCheck'
__download_url__ = 'https://github.com/reyeon1209/PressCheck'
__install_requires__ = [
    'absl-py',
    'astor==0.8.1',
    'astunparse==1.6.3',
    'beautifulsoup4==4.6.0',
    'blinker==1.4',
    'brotlipy==0.7.0',
    'cachetools',
    'certifi==2020.11.8',
    'cffi',
    'chardet',
    'click==7.1.2',
    'colorama==0.4.4',
    'cryptography',
    'cssselect==1.1.0',
    'dataclasses==0.6',
    'decorator==4.4.2',
    'dnspython==1.16.0',
    'fasttext==0.9.2',
    'feedparser==5.2.1',
    'filelock==3.0.12',
    'future==0.18.2',
    'gast==0.3.3',
    'google-auth',
    'google-auth-oauthlib',
    'google-pasta==0.2.0',
    'goose3==3.1.6',
    'grpcio',
    'h5py==2.10.0',
    'idna',
    'importlib-metadata',
    'jieba==0.42.1',
    'joblib==0.17.0',
    'JPype1==1.1.2',
    'Keras-Applications',
    'Keras-Preprocessing==1.1.2',
    'kobert-transformers==0.4.1',
    'konlpy==0.5.2',
    'krwordrank==1.0.3',
    'lxml==4.6.1',
    'Markdown',
    'mkl-fft==1.2.0',
    'mkl-random==1.1.1',
    'mkl-service==2.3.0',
    'networkx',
    'nltk==3.5',
    'numpy==1.18.5',
    'oauthlib==3.1.0',
    'olefile==0.46',
    'opt-einsum==3.1.0',
    'packaging==20.4',
    'Pillow',
    'protobuf==3.14.0',
    'pyasn1==0.4.8',
    'pyasn1-modules==0.2.8',
    'pybind11==2.6.1',
    'pycparser',
    'PyJWT==1.7.1',
    'pymongo==3.11.0',
    'pyOpenSSL',
    'pyparsing==2.4.7',
    'pyreadline==2.1',
    'PySocks',
    'python-dateutil==2.8.1',
    'regex==2020.11.13',
    'requests==2.25.0',
    'requests-oauthlib==1.3.0',
    'rsa',
    'sacremoses==0.0.43',
    'scikit-learn==0.23.2',
    'scipy==1.4.1',
    'sentencepiece==0.1.91',
    'six',
    'sklearn==0.0',
    'soupsieve==2.0.1',
    'tensorboard',
    'tensorboard-plugin-wit==1.6.0',
    'tensorflow==2.1.0',
    'tensorflow-estimator==2.1.0',
    'tensorflow-gpu==2.3.1',
    'tensorflow-gpu-estimator==2.3.0',
    'termcolor==1.1.0',
    'threadpoolctl==2.1.0',
    'tokenizers==0.9.3'
    'torch==1.7.0',
    'torchaudio==0.7.0',
    'torchvision==0.8.1',
    'tqdm==4.53.0',
    'transformers==3.5.1',
    'tweepy==3.9.0',
    'typing-extensions',
    'urllib3==1.26.2',
    'Werkzeug==0.16.1',
    'win-inet-pton',
    'wincertstore==0.2',
    'wrapt==1.12.1',
    'zipp',
    'feedparser'

]
__license__ = 'MIT'


from presscheck.crawler import *
from presscheck.mailing import *
from presscheck.mostRead import *
from presscheck.similarity import *
from presscheck.summaries import *
from presscheck.todays import *
from presscheck.updateKeySum import *
