# -*- coding: utf-8 -*-
"""ArticleCollector.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sicDVAdpC0X0q_cYkl8fPGNPrEnE2cYa

**1. Feedparser package 설치**

flask를 패키지화하거나 requiremets.txt로 freezing
"""

!pip install feedparser

"""**2.데이터 타입 작성**"""

import feedparser

rss_dic = []
cl = ['전체','정치','사회','경제','국제','스포츠','문화']                         #category list
pl = ['조선일보','중앙일보','동아일보','KBS','SBS','국민일보','연합뉴스']         #press list
donga_url = ['https://rss.donga.com/total.xml','https://rss.donga.com/politics.xml','https://rss.donga.com/national.xml','https://rss.donga.com/economy.xml',
             'https://rss.donga.com/international.xml','https://rss.donga.com/sports.xml','https://rss.donga.com/culture.xml']
#동아일보의 전체,정치,사회,경제,국제,스포츠,문화 7개 카테고리의 RSS주소
class article:
  id=0
  title=0
  contents=0
  keywords=[]
  def GetKeywords():pass


i=0

for rss in donga_url:
  if rss == None:
    break
  else:
    parse_rss = feedparser.parse(rss)
    for p in parse_rss.entries:
      rss_dic.append({'title':p.title,'link':p.link,'category':cl[i]})
      i+=1
print(rss_dic)

"""**2.수집**"""